[server]
address = "0.0.0.0:3000"
domain = "zubr.chat"

[storage]
users_file = "data/users.json"

[irc]
inspircd_path = "/home/micr0/Documents/inspircd/run/inspircd"
config_path = "/home/micr0/Documents/inspircd/run/conf"
auto_start = true  # Set to true to automatically start/manage InspIRCd
